import type { Customer } from "@/types/customer";

export const customersMock: Customer[] = [
  {
    id: "1",
    name: "Comercial ABC Ltda",
    tradeName: "Comercial ABC",
    document: "12.345.678/0001-90",
    city: "São Paulo",
    state: "SP",
    salesperson: "João Silva",
    status: "ACTIVE",
    erpStatus: "SYNCED",
    erpCustomerKey: 10,
    createdAt: "2026-08-01T10:00:00",
  },
  {
    id: "2",
    name: "Distribuidora Alfa Ltda",
    tradeName: "Distribuidora Alfa",
    document: "23.456.789/0001-10",
    city: "Campinas",
    state: "SP",
    salesperson: "Maria Santos",
    status: "ACTIVE",
    erpStatus: "SYNCED",
    erpCustomerKey: 32,
    createdAt: "2026-08-05T14:00:00",
  },
  {
    id: "3",
    name: "Empresa XYZ Comércio",
    tradeName: "Empresa XYZ",
    document: "34.567.890/0001-20",
    city: "Curitiba",
    state: "PR",
    salesperson: "Carlos Souza",
    status: "ACTIVE",
    erpStatus: "PENDING",
    createdAt: "2026-08-10T09:00:00",
  },
  {
    id: "4",
    name: "Comercial Beta Ltda",
    tradeName: "Comercial Beta",
    document: "45.678.901/0001-30",
    city: "Joinville",
    state: "SC",
    status: "ACTIVE",
    erpStatus: "NOT_LINKED",
    createdAt: "2026-08-12T11:00:00",
  },
  {
    id: "5",
    name: "Indústria Delta S.A.",
    tradeName: "Delta",
    document: "56.789.012/0001-40",
    city: "Belo Horizonte",
    state: "MG",
    salesperson: "João Silva",
    status: "INACTIVE",
    erpStatus: "ERROR",
    erpCustomerKey: 89,
    createdAt: "2026-08-15T16:00:00",
  },
];
